name: Rebase

on:
  schedule:
    - cron: '40 23 * * *'

jobs:
  build:
    name: Automatic rebase
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/droid-legacy/android_vendor_lineage.git -b lineage-18.1
        cd android_vendor_lineage
        git fetch https://github.com/LineageOS/android_vendor_lineage.git lineage-18.1
        git rebase FETCH_HEAD
        git push -f
        git checkout lineage-19.1
        git fetch https://github.com/LineageOS/android_vendor_lineage.git lineage-19.1
        git rebase FETCH_HEAD
        git push -f
        git checkout lineage-20.0
        git fetch https://github.com/LineageOS/android_vendor_lineage.git lineage-20.0
        git rebase FETCH_HEAD
        git push -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
